#!/bin/bash -e

#
# Copyright © 2023 David Dunwoody.
#
# All rights reserved.
#

VERSION="$(git describe)"
TARGET="$(basename $PWD)"

echo Building "${VERSION}" distribution...

(cd .. && ./_build_plugin "${TARGET}")

DIST_DIR="../target/dist/${TARGET}"
echo "${TARGET}: $VERSION" > "${DIST_DIR}/VERSION"
(cd ../target/dist && zip -rq "${TARGET}-${VERSION}.zip" "${TARGET}")

echo "${TARGET} distribution built at ../target/dist/${TARGET}-${VERSION}.zip"








